include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

authentication-service-deploy:
  stage: deploy
  extends:
    - .setup-credentials
    - .setup-image
  needs:
    - job: authentication-service-publish-image
      artifacts: true

  script:
    - cd $K8S_DIR/overlays/dev-k8s/authentication-service

    - kustomize edit set image $PROJECT_NAME=$IMAGE_ECR_TAG

    - kubectl apply -k .