publish:
  stage: publish
  needs:
    - job: test
      artifacts: true

  script:
    - cd $PROJECT_DIR

    - docker_login

    - |
      docker build \
      --push \
      --platform linux/amd64 \
      --build-arg AWS_CODEARTIFACT_AUTH_TOKEN=$AWS_CODEARTIFACT_AUTH_TOKEN \
      -t $PROJECT_IMAGE_ECR_TAG:latest \
      .
      
      #-t $PROJECT_IMAGE_ECR_TAG:$CI_COMMIT_SHORT_SHA \