include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

shared-starter-publish-artifact:
  stage: publish
  extends:
    - .setup-credentials
    - .setup-image
  needs:
    - job: shared-starter-test
      artifacts: true

  script:
    - cd $SHARED_STARTER_ARTIFACT_DIR
    - chmod +x ./gradlew
    - ./gradlew publish --build-cache --parallel
