include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

shared-starter-publish-artifact:
  stage: publish
  extends:
    - .setup-gradle
  needs:
    - job: shared-starter-test
      artifacts: true
  image: haidranoid/gitlab-ci-java21:latest


  script:
    - cd $SHARED_STARTER_ARTIFACT_DIR
    - chmod +x ./gradlew
    - ./gradlew publish --build-cache --parallel
