include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'
  - local: '/infra/ci/gitlab/templates/stages-rules.yml'

test:
  stage: test
  extends:
    - .setup-gradle
    - .stages-rules-shared-starter
  image:
    name: haidranoid/gitlab-ci-java21:latest
    pull_policy: if-not-present

  script:
    - cd $SHARED_STARTER_ARTIFACT_DIR
    - chmod +x ./gradlew
    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - $SHARED_STARTER_ARTIFACT_DIR/build/libs/*.jar
      - $SHARED_STARTER_ARTIFACT_DIR/build/reports/tests/test
    reports:
      junit:
        - $SHARED_STARTER_ARTIFACT_DIR/build/test-results/test/*.xml