include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

shared-starter-test:
  stage: test
  extends:
    - .setup-credentials
    - .setup-image

  script:
    - cd $SHARED_STARTER_ARTIFACT_DIR
    - chmod +x ./gradlew
    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - $ARTIFACT_RELATIVE_PATH_DIR/build/libs/*.jar
      - $ARTIFACT_RELATIVE_PATH_DIR/build/reports/tests/test
    reports:
      junit:
        - $ARTIFACT_RELATIVE_PATH_DIR/build/test-results/test/*.xml