apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: config-server
          image: ${PROJECT_IMAGE_ECR_TAG}:latest
          imagePullPolicy: Always