variables:
  PROJECT_RELATIVE_PATH_DIR: $PROJECT_DIR/$PROJECT_NAME
  GRADLE_USER_HOME: /cache/gradle/$PROJECT_NAME
  GRADLE_OPTS: >-
    -Dorg.gradle.daemon=false
    -Dorg.gradle.parallel=true
    -Dorg.gradle.caching=true

default:
  before_script:
    - cd infra/scripts
    - . env.sh

    - echo "Authenticate aws credentials"
    - . $AWS_SCRIPTS_DIR/utils.sh
    - setup_aws_env v1

    - echo "AWS_ECR_REPOSITORY_URL=$AWS_ECR_REPOSITORY_URL" >> aws.env
    - echo "AWS_ECR_AUTH_PASSWORD=$AWS_ECR_AUTH_PASSWORD" >> aws.env
    - echo "AWS_CODEARTIFACT_AUTH_TOKEN=$AWS_CODEARTIFACT_AUTH_TOKEN" >> aws.env

    - cd ../../

  artifacts:
    reports:
      dotenv: aws.env