#!/bin/sh

PROJECT_DOCKERFILE=""

if [ "$PROJECT_ARTIFACT_LANG" = "$ARTIFACT_LANG_DOTNET" ]; then
  PROJECT_DOCKERFILE="$PROJECT_NAME_SOLUTION/Dockerfile"
elif [ "$PROJECT_ARTIFACT_LANG" = "$ARTIFACT_LANG_JAVA" ]; then
  PROJECT_DOCKERFILE="Dockerfile"
fi

export PROJECT_DOCKERFILE

export PROJECT_K8S_KUSTOMIZATION_DIR="$K8S_DEV_LOCAL_MICROSERVICES_DIR/$PROJECT_NAME"