#!/bin/sh

PROJECT_DIR=""
PROJECT_DOCKERFILE=""
PROJECT_K8S_KUSTOMIZATION_DIR=""

if [ "$PROJECT_TYPE" = "$PROJECT_TYPE_LIBRARY_JAVA" ]; then
    
    PROJECT_DIR="$LIBRARIES_DIR/$PROJECT_NAME"
    
elif [ "$PROJECT_TYPE" = "$PROJECT_TYPE_LIBRARY_DOTNET" ]; then
  
    PROJECT_DIR="$LIBRARIES_DIR/$PROJECT_NAME"
    
elif [ "$PROJECT_TYPE" = "$PROJECT_TYPE_MICROSERVICE_JAVA" ]; then
  
    PROJECT_DIR="$MICROSERVICES_DIR/$PROJECT_NAME"
    PROJECT_DOCKERFILE="$PROJECT_DIR/Dockerfile"
    PROJECT_K8S_KUSTOMIZATION_DIR="$K8S_DEV_LOCAL_MICROSERVICES_DIR/$PROJECT_NAME"
    
elif [ "$PROJECT_TYPE" = "$PROJECT_TYPE_MICROSERVICE_DOTNET" ]; then
  
    PROJECT_DIR="$MICROSERVICES_DIR/$PROJECT_NAME"
    PROJECT_DOCKERFILE="$PROJECT_DIR/$PROJECT_NAME_SOLUTION/Dockerfile"
    PROJECT_K8S_KUSTOMIZATION_DIR="$K8S_DEV_LOCAL_MICROSERVICES_DIR/$PROJECT_NAME"
    
fi

export PROJECT_DIR
export PROJECT_DOCKERFILE
export PROJECT_K8S_KUSTOMIZATION_DIR


