#!/bin/sh

if [ "$PROJECT_TYPE" = "$PROJECT_TYPE_LIBRARY_JAVA" ]; then
    export PROJECT_DIR="$LIBRARIES_DIR/$PROJECT_NAME"
elif [ "$PROJECT_TYPE" = "$PROJECT_TYPE_LIBRARY_DOTNET" ]; then
    export PROJECT_DIR="$LIBRARIES_DIR/$PROJECT_NAME"
elif [ "$PROJECT_TYPE" = "$PROJECT_TYPE_MICROSERVICE_JAVA" ]; then
    export PROJECT_DIR="$MICROSERVICES_DIR/$PROJECT_NAME"
elif [ "$PROJECT_TYPE" = "$PROJECT_TYPE_MICROSERVICE_DOTNET" ]; then
    export PROJECT_DIR="$MICROSERVICES_DIR/$PROJECT_NAME"
fi




