spring:
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: authentication-service
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/api/v1/auth/**
            - id: accounts-service
              uri: http://host.docker.internal:8081
              predicates:
                - Path=/api/v1/accounts/**