test:
  stage: test
  script:
    - cd $PROJECT_DIR
    - echo $PROJECT_DIR
    - echo $PROJECT_NAME
    - chmod +x ./gradlew
    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - $PROJECT_DIR/build/reports/tests/test
    reports:
      junit:
        - $PROJECT_DIR/build/test-results/test/*.xml