variables:
  GIT_DEPTH: 0
  GRADLE_OPTS: >-
    -Dorg.gradle.daemon=false
    -Dorg.gradle.parallel=true
    -Dorg.gradle.caching=true

#include: 
#  local: 'infra/ci/gitlab/setup-env.yml'
default:
  image:
    name: haidranoid/gitlab-ci-java21:latest
    pull_policy: if-not-present
  before_script:
    - cd infra/scripts
    - . setup-env.sh
    - setup_aws_env v1
    - cd ..

shared-starter-workflow:
  variables:
    PROJECT_NAME: shared-starter
    PROJECT_DIR: $ARTIFACTS_DIR/$PROJECT_NAME
  trigger:
    include:
      - local: '$PROJECT_DIR/.gitlab-ci.yml'
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      changes:
        - $PROJECT_DIR/**/*
        - $GITLAB_TEMPLATES_DIR/$PROJECT_DIR/**/*

config-server-workflow:
  variables:
    PROJECT_NAME: config-server
    PROJECT_DIR: $SERVICES_DIR/$PROJECT_NAME
  trigger:
    include:
      - local: '$PROJECT_DIR/.gitlab-ci.yml'
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      changes:
        - $PROJECT_DIR/**/*
        - $INFRA_DIR/ci/gitlab/templates/$PROJECT_DIR/**/*

accounts-service-workflow:
  variables:
    PROJECT_NAME: accounts-service
    PROJECT_DIR: $SERVICES_DIR/$PROJECT_NAME
  trigger:
    include:
      - local: '$PROJECT_DIR/.gitlab-ci.yml'
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      changes:
        - $PROJECT_DIR/**/*
        - $INFRA_DIR/ci/gitlab/templates/$PROJECT_DIR/**/*

authentication-service-workflow:
  variables:
    PROJECT_NAME: authentication-service
    PROJECT_DIR: $SERVICES_DIR/$PROJECT_NAME
  trigger:
    include:
      - local: '$PROJECT_DIR/.gitlab-ci.yml'
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      changes:
        - $PROJECT_DIR/**/*
        - $INFRA_DIR/ci/gitlab/templates/$PROJECT_DIR/**/*

gateway-workflow:
  variables:
    PROJECT_NAME: gateway
    PROJECT_DIR: $SERVICES_DIR/$PROJECT_NAME
  trigger:
    include:
      - local: '$PROJECT_DIR/.gitlab-ci.yml'
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      changes:
        - $PROJECT_DIR/**/*
        - $INFRA_DIR/ci/gitlab/templates/$PROJECT_DIR/**/*