#!/bin/sh

set -eu

#TODO: validate the vars used here
PROJECT_IMAGE_TAG="$AWS_ECR_DSA_REPOSITORY_NAME/$PROJECT_NAME"
PROJECT_IMAGE_ECR_TAG="$AWS_ECR_REGISTRY_URL/$PROJECT_IMAGE_TAG"

export PROJECT_IMAGE_TAG
export PROJECT_IMAGE_ECR_TAG