spring:
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
application:
  endpoints:
    accounts-service-endpoint: http://localhost:8082/api/v1/accounts
    accounts-service-internal-endpoint: http://localhost:8082/api/v1/internal/accounts