include:
  - local: '/infra/ci/gitlab/templates/images/accounts-service/test.yml'
  - local: '/infra/ci/gitlab/templates/images/accounts-service/publish.yml'

default:
  tags:
    - local

stages:
  - test
  - publish