include:
  - local: '/infra/ci/gitlab/templates/before-script.yml'
  - local: '/infra/ci/gitlab/templates/images/accounts-service/test.yml'
  - local: '/infra/ci/gitlab/templates/images/accounts-service/publish.yml'

stages:
  - test
  - publish

default:
  tags:
    - local

variables:
  PROJECT_NAME: accounts-service
  PROJECT_DIR: services