include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

build:
  stage: build
  extends:
    - .setup-gradle
  needs:
    - test
  image:
    name: haidranoid/gitlab-ci-java21:latest
    pull_policy: if-not-present

  script:
    - cd services/config-server
    - chmod +x ./gradlew
    - ./gradlew build -x test --build-cache --parallel

  artifacts:
    when: on_success
    paths:
      - services/services-starter/build/libs/*.jar