include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

config-server-deploy:
  stage: deploy
  extends:
    - .setup-gradle
    - .setup-credentials
    - .setup-image
  needs:
    - job: config-server-publish-image
      artifacts: true
  variables:
    SERVICE_NAME: config-server

  script:
    - cd $K8S_DIR/overlays/dev-k8s/config-server

    - kustomize edit set image $SERVICE_NAME=$IMAGE_ECR_TAG

    - kubectl apply -k .