include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

config-server-test:
  stage: test
  extends:
    - .setup-credentials
    - .setup-image

  script:
    - cd $CONFIG_SERVER_DIR
    - chmod +x ./gradlew
    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - $PROJECT_RELATIVE_PATH_DIR/build/reports/tests/test
    reports:
      junit:
        - $PROJECT_RELATIVE_PATH_DIR/build/test-results/test/*.xml