include:
  - local: '/infra/ci/gitlab/templates/artifacts/setup-env.yml'

build:
  stage: build
  image: amazoncorretto:21-alpine3.23-jdk
  extends:
    - .setup-gradle
  needs:
    - test

  script:
    - ./gradlew assemble -x test --build-cache --parallel

  artifacts:
    when: on_success
    paths:
      - build/libs/*.jar