variables:
  GRADLE_OPTS: >-
    -Dorg.gradle.daemon=false
    -Dorg.gradle.parallel=true
    -Dorg.gradle.caching=true

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  image: amazoncorretto:21-alpine3.23-jdk

  script:
    - cd services/services-starter

    - chmod +x ./gradlew

    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - build/reports/tests/test
    reports:
      junit:
        - build/test-results/test/*.xml