variables:
  GRADLE_OPTS: >-
    -Dorg.gradle.daemon=false
    -Dorg.gradle.parallel=true
    -Dorg.gradle.caching=true

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  image: amazoncorretto:21-alpine3.23-jdk

  script:
    - echo "Installing aws-cli..."
    - apk add --no-cache aws-cli

    - echo "Setting aws credentials..."
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

    - echo "Validating AWS credentials..."
    - aws configure list

    - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain artifacts --query authorizationToken --output text)

    - cd services/services-starter

    - chmod +x ./gradlew

    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - services/services-starter/build/reports/tests/test
    reports:
      junit:
        - services/services-starter/build/test-results/test/*.xml