services:
  config-server-srv:
    image: config-server:dev-compose
    build:
      context: ../../../services/config-server
      dockerfile: ../../../services/config-server/Dockerfile
    volumes:
      - ../../../../distributed-systems-architecture-properties:/dsa-properties-repository
    environment:
      SPRING_PROFILES_ACTIVE: native
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 20

  authentication-service-srv:
    image: authentication-service:dev-compose
    build:
      context: ../../../services/authentication-service
      dockerfile: ../../../services/authentication-service/Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8080:8080"
    depends_on:
      config-server-srv:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  accounts-service-srv:
    image: accounts-service:dev-compose
    build:
      context: ../../../services/accounts-service
      dockerfile: ../../../services/accounts-service/Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8081:8081"
    depends_on:
      config-server-srv:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  audit-service-srv:
    image: audit-service:dev-compose
    build:
      context: ../../../services/audit-service
      dockerfile: ../../../services/audit-service/Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8082:8082"
    depends_on:
      config-server-srv:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway-srv:
    image: gateway:dev-compose
    build:
      context: ../../../services/gateway
      dockerfile: ../../../services/gateway/Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8222:8222"
    depends_on:
      config-server-srv:
        condition: service_healthy
      authentication-service-srv:
        condition: service_started
      accounts-service-srv:
        condition: service_started
      audit-service-srv:
        condition: service_started

networks:
  default:
    external: true
    name: distributed-systems