include:
  - local: '/infra/ci/gitlab/templates/images/config-server/test.yml'
  - local: '/infra/ci/gitlab/templates/images/config-server/publish-image.yml'

workflow:
  name: config-server-workflow
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      changes:
        - services/config-server/**/*

stages:
  - test
  - publish