include:
  - local: '$GITLAB_DIR/setup-env.yml'
  - local: '$GITLAB_TEMPLATES_DIR/$PROJECT_DIR/test.yml'
  - local: '$GITLAB_TEMPLATES_DIR/$PROJECT_DIR/publish.yml'

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local