spring:
  cloud:
    config:
      server:
        native:
          search-locations:
          - "file://${user.home:./}/MyProjects/distributed-systems-architecture-properties"
          - file:///dsa-properties-repository