include:
  - local: $GITLAB_CI_BOOTSTRAP_DIR/setup-java.yml
  - local: $GITLAB_CI_TEMPLATES_MICROSERVICES_DIR/test-java.yml
  - local: $GITLAB_CI_TEMPLATES_MICROSERVICES_DIR/publish-java.yml
  - local: $GITLAB_CI_TEMPLATES_MICROSERVICES_DIR/deploy-java.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local
    - java
    - microservice