include:
  - local: /infrastructure/gitlab-ci/bootstrap/setup-dotnet.yml
  - local: /infrastructure/gitlab-ci/templates/test-microservice-dotnet.yml
  - local: /infrastructure/gitlab-ci/templates/publish-microservice-dotnet.yml
  - local: /infrastructure/gitlab-ci/templates/deploy-microservice-dotnet.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local
    - dotnet
    - microservice