include:
  - local: /infrastructure/gitlab-ci/bootstrap/setup-java.yml
  - local: /infrastructure/gitlab-ci/templates/libraries/test-java.yml
  - local: /infrastructure/gitlab-ci/templates/libraries/publish-java.yml
  - local: /infrastructure/gitlab-ci/templates/libraries/deploy-java.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local
    - java
    - library