include:
  - local: $GITLAB_CI_BOOTSTRAP_DIR/setup-dotnet.yml
  - local: $GITLAB_CI_TEMPLATES_MICROSERVICES_DIR/test-dotnet.yml
  - local: $GITLAB_CI_TEMPLATES_MICROSERVICES_DIR/publish-dotnet.yml
  - local: $GITLAB_CI_TEMPLATES_MICROSERVICES_DIR/deploy-dotnet.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local
    - dotnet
    - microservice