include:
  - local: infrastructure/gitlab-ci/bootstrap/setup-dotnet.yml
  - local: infrastructure/gitlab-ci/templates/microservices/test-dotnet.yml
  - local: infrastructure/gitlab-ci/templates/microservices/publish-dotnet.yml
  - local: infrastructure/gitlab-ci/templates/microservices/deploy-dotnet.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local
    - dotnet
    - microservice