include:
  - local: $GITLAB_CI_TEMPLATES_DIR/$LIBRARIES_DIR/test-java.yml
  - local: $GITLAB_CI_TEMPLATES_DIR/$LIBRARIES_DIR/publish-java.yml
  - local: $GITLAB_CI_TEMPLATES_DIR/$LIBRARIES_DIR/deploy-java.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local
    - java