include:
  - local: $PROJECT_TEMPLATES_DIR/test-java.yml
  - local: $PROJECT_TEMPLATES_DIR/publish-java.yml
  - local: $PROJECT_TEMPLATES_DIR/deploy-java.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local
    - java