plugins {
    id 'java-library'
    id 'io.freefair.lombok' version '9.5.0'
    id 'maven-publish'
}

group = 'org.dsa.shared'
version = '2.0.0'
description = 'core'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    enabled = true
}

repositories {
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = group.toString()
            artifactId = project.name
            version = version.toString()
            from components.java
        }
    }

    repositories {

        def codeArtifactAuthToken = System.getenv("AWS_CODEARTIFACT_AUTH_TOKEN")

        if (!codeArtifactAuthToken) {
            codeArtifactAuthToken = providers.exec {
                commandLine 'aws', 'codeartifact', 'get-authorization-token',
                        '--domain', 'artifacts',
                        '--query', 'authorizationToken',
                        '--output', 'text'
            }.standardOutput.asText.get().trim()
        }

        maven {
            url 'https://artifacts-314812911342.d.codeartifact.us-east-1.amazonaws.com/maven/shared/'
            credentials {
                username "aws"
                password codeArtifactAuthToken
            }
        }
    }
}

ext {
    set('springBootVersion', "4.0.6")
}

dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")

    api 'io.jsonwebtoken:jjwt-api:0.13.0'
    api 'org.springframework.security:spring-security-core'
    api 'org.springframework.boot:spring-boot-starter-kafka'
    api 'org.springframework:spring-web'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}