spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update