namespace: k8s-local

resources:
  - namespace.yml
  - configmap.yml
  - ../../base

patches:
  - path: accounts-service/deployment-patch.yml
  - path: authentication-service/deployment-patch.yml
  - path: config-server/deployment-patch.yml
  - path: gateway/deployment-patch.yml

  #- path: gateway/service-patch.yml

