server:
  port: 8080
spring:
  application:
    name: authentication-service
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health, info