spring:
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_service_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
application:
  endpoints:
    accounts-service-endpoint: http://localhost:8081/api/v1/accounts
    accounts-service-internal-endpoint: http://localhost:8081/api/v1/internal/accounts