.setup-credentials:
  before_script:
    - cd infra/scripts
    - . env.sh

    - echo "Authenticate aws credentials"
    - . $AWS_SCRIPTS_DIR/utils.sh
    - setup_aws_env v1

    - cd ../../

  after_script:
    - echo "AWS_ECR_REGISTRY_URL=$AWS_ECR_REGISTRY_URL" >> aws.env
    - echo "AWS_ECR_AUTH_PASSWORD=$AWS_ECR_AUTH_PASSWORD" >> aws.env
    - echo "AWS_CODEARTIFACT_AUTH_TOKEN=$AWS_CODEARTIFACT_AUTH_TOKEN" >> aws.env

  artifacts:
    reports:
      dotenv: $SERVICE_RELATIVE_PATH_DIR/aws.env

.setup-image:
  image:
    name: haidranoid/gitlab-ci-java21:latest
    pull_policy: if-not-present