.stages-rules-config-server:
  rules:
    - changes:
        - $CONFIG_SERVER_DIR/**/*
        - $CI_DIR/**/*

.stages-rules-shared-starter:
  rules:
    - changes:
        - $SHARED_STARTER_ARTIFACT_DIR/**/*
        - $CI_DIR/**/*