include:
  - local: '/infra/ci/gitlab/templates/before-script.yml'
  - local: '/infra/ci/gitlab/templates/images/gateway/test.yml'
  - local: '/infra/ci/gitlab/templates/images/gateway/publish.yml'

stages:
  - test
  - publish

default:
  tags:
    - local

variables:
  PROJECT_NAME: gateway
  PROJECT_DIR: services
