include:
  - local: '/infra/ci/gitlab/templates/images/gateway/test.yml'
  - local: '/infra/ci/gitlab/templates/images/gateway/publish.yml'

default:
  tags:
    - local

variables:
  SERVICE_NAME: gateway
  SERVICE_DIR: /services/gateway
  SERVICE_FULL_PATH_DIR: $CI_PROJECT_DIR/$SERVICE_DIR

  GRADLE_USER_HOME: $SERVICE_FULL_PATH_DIR/.gradle

stages:
  - test
  - publish