deploy:
  stage: deploy
  when: manual
  needs:
    - job: publish
      artifacts: true

  script:
    - cd $INFRA_DIR/k8s/overlays/k8s-local

    - |
      kubectl create secret docker-registry ecr-credentials \
      -n k8s-local \
      --docker-password=$AWS_ECR_AUTH_PASSWORD \
      --docker-username=AWS \
      --docker-server=$AWS_ECR_REGISTRY_URL \
      --dry-run=client -o yaml | kubectl apply -n k8s-local -f -

    - kubectl kustomize . | envsubst | kubectl apply -f -

    - kubectl rollout status deployment/$PROJECT_NAME -n k8s-local