deploy:
  stage: deploy
  when: manual
  needs:
    - job: publish
      artifacts: true

  script:
    - cd $INFRA_DIR/k8s/overlays/k8s-local

    - kubectl kustomize . | envsubst | kubectl apply -f - -n k8s-local