.setup-gradle:
  variables:
    GRADLE_OPTS: >-
      -Dorg.gradle.daemon=false
      -Dorg.gradle.parallel=true
      -Dorg.gradle.caching=true

  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches