.setup-gradle:
  variables:
    GRADLE_USER_HOME: /cache/gradle
    GRADLE_OPTS: >-
      -Dorg.gradle.daemon=false
      -Dorg.gradle.parallel=true
      -Dorg.gradle.caching=true

  #cache:
  #  paths:
  #    - .gradle/wrapper
  #    - .gradle/caches

  before_script:
    - cd infra
    - . env.sh

    - echo "Authenticate aws credentials"
    - . $AWS_SCRIPTS_DIR/utils.sh
    - setup_aws_env v1

    - cd ../