apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: authentication-service
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: dev-k8s-configmap
                  key: SPRING_PROFILES_ACTIVE