plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.freefair.lombok' version '9.5.0'
    id 'maven-publish'
    id 'jacoco'
}

group = 'org.dsa.services'
version = '2.0.0'
description = 'accounts-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = "${project.name}.jar"
}

repositories {
    mavenLocal()

    def codeArtifactAuthToken = System.getenv("AWS_CODEARTIFACT_AUTH_TOKEN")

    try {
        if (!codeArtifactAuthToken) {

            providers.exec {
                commandLine 'aws', 'login'
            }

            codeArtifactAuthToken = providers.exec {
                commandLine 'aws', 'codeartifact', 'get-authorization-token',
                        '--domain', 'artifacts',
                        '--query', 'authorizationToken',
                        '--output', 'text'
            }.standardOutput.asText.get().trim()
        }

        maven {
            url 'https://artifacts-314812911342.d.codeartifact.us-east-1.amazonaws.com/maven/shared/'
            credentials {
                username "aws"
                password codeArtifactAuthToken
            }
        }
    } catch (Exception ignored) {
        mavenCentral()
    }
}

jacoco {
    toolVersion = "0.8.11"
}

jacocoTestReport {
    dependsOn test

    classDirectories.setFrom(
            files(classDirectories.files.collect {
                fileTree(dir: it, exclude: [
                        '**/*Application*',
                        '**/config/**',
                        '**/constants/**',
                        '**/entity/**',
                        '**/properties/**',
                        '**/request/**',
                        '**/response/**',
                        '**/utils/**',
                ])
            })
    )

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport

    violationRules {
        rule {
            element = 'CLASS'

            excludes = [
                    '*Application*',
                    '*config*',
                    '*controller*',
                    '*constants*',
                    '*entity*',
                    '*properties*',
                    '*request*',
                    '*response*',
                    '*utils*',
            ]

            limit {
                counter = 'BRANCH'
                value = 'COVEREDRATIO'
                minimum = 0.80
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification

dependencies {
    implementation 'org.dsa.shared:shared-starter:2.0.0'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.dsa.shared:shared-starter-test:2.0.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


tasks.named('test') {
    useJUnitPlatform()
    //jvmArgs "-javaagent:${configurations.testRuntimeClasspath.find { it.name.contains('mockito-core') }}", '-Xshare:off'
    jvmArgs "-javaagent:${configurations.testRuntimeClasspath.find { it.name.contains('mockito-core') }.absolutePath}"
}

test {
    systemProperty "spring.cloud.config.enabled", "false"
    systemProperty "spring.cloud.config.import-check.enabled", "false"
}