default:
  image:
    name: haidranoid/gitlab-ci-java21:latest
    pull_policy: if-not-present

  before_script:
    - cd infra/scripts
    - . setup-env.sh

    - echo "Authenticate aws credentials"
    - setup_aws_env v1

    - echo "Assigns docker image tags"
    - setup_images_env

    - cd ../../