plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.freefair.lombok' version '9.5.0'
    id 'maven-publish'
}

group = 'org.dsa.shared'
version = '2.0.0'
description = 'starter'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    enabled = true
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenLocal()

    def codeArtifactAuthToken = System.getenv("AWS_CODEARTIFACT_AUTH_TOKEN")

    try {
        if (!codeArtifactAuthToken) {

            //providers.exec {
            //    commandLine 'aws', 'login'
            //}

            codeArtifactAuthToken = providers.exec {
                commandLine 'aws', 'codeartifact', 'get-authorization-token',
                        '--domain', 'artifacts',
                        '--query', 'authorizationToken',
                        '--output', 'text'
            }.standardOutput.asText.get().trim()
        }

        maven {
            url 'https://artifacts-314812911342.d.codeartifact.us-east-1.amazonaws.com/maven/shared/'
            credentials {
                username "aws"
                password codeArtifactAuthToken
            }
        }
    } catch (Exception ignored) {
        mavenCentral()
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = group.toString()
            artifactId = project.name
            version = version.toString()
            from components.java
        }
    }

    repositories {

        def codeArtifactAuthToken = System.getenv("AWS_CODEARTIFACT_AUTH_TOKEN")

        if (!codeArtifactAuthToken) {
            /*
            providers.exec {
                commandLine 'aws', 'login'
            }
            */
            codeArtifactAuthToken = providers.exec {
                commandLine 'aws', 'codeartifact', 'get-authorization-token',
                        '--domain', 'artifacts',
                        '--query', 'authorizationToken',
                        '--output', 'text'
            }.standardOutput.asText.get().trim()
        }

        maven {
            url 'https://artifacts-314812911342.d.codeartifact.us-east-1.amazonaws.com/maven/shared/'
            credentials {
                username "aws"
                password codeArtifactAuthToken
            }
        }
    }
}

ext {
    set('springBootVersion', "4.0.6")
    set('springCloudVersion', "2025.1.1")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {
    // Shared core API
    api 'org.dsa.shared:shared-core:2.0.0'

    // Spring Boot
    api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    api 'org.springframework.boot:spring-boot-autoconfigure'

    api 'org.springframework.boot:spring-boot-starter-actuator'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.boot:spring-boot-starter-webclient'
    api 'org.springframework.boot:spring-boot-starter-webmvc'
    api 'org.springframework.cloud:spring-cloud-starter-config'

    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
    api 'org.springframework.security:spring-security-oauth2-jose'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    // Required launcher to execute tests on the JVM
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}