deploy:
  stage: deploy
  needs:
    - job: publish
      artifacts: true

  script:
    - cd $K8S_DIR/overlays/dev-k8s/gateway

    - kustomize edit set image $PROJECT_NAME=$PROJECT_IMAGE_ECR_TAG

    - kubectl apply -k .