apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: authentication-service
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: k8s-local-configmap
                  key: SPRING_PROFILES_ACTIVE