#!/bin/sh

# export SCRIPTS_DIR="$DSA_DIR/scripts" -> already exported in $DSA_DIR/bootstrap.sh
export INFRASTRUCTURE_DIR="$DSA_DIR/infrastructure"
export LIBRARIES_DIR="$DSA_DIR/libraries"
export MICROSERVICES_DIR="$DSA_DIR/microservices"

export DOCKER_DIR="$INFRASTRUCTURE_DIR/docker"
export GITLAB_CI_DIR="$INFRASTRUCTURE_DIR/gitlab-ci"
export K8S_DIR="$INFRASTRUCTURE_DIR/k8s"

export DOCKER_COMPOSES_DIR="$DOCKER_DIR/composes"
export DOCKER_IMAGES_DIR="$DOCKER_DIR/images"

export GITLAB_CI_BOOTSTRAP_DIR="$GITLAB_CI_DIR/bootstrap"
export GITLAB_CI_TEMPLATES_DIR="$GITLAB_CI_DIR/templates"

export K8S_BASE_DIR="$K8S_DIR/base"
export K8S_OVERLAYS_DIR="$K8S_DIR/overlays"

export COMPOSE_KAFKA_DIR="$DOCKER_COMPOSES_DIR/kafka"
export COMPOSE_SERVICES_DIR="$DOCKER_COMPOSES_DIR/microservices"
export COMPOSE_KAFKA_FILE="$COMPOSE_KAFKA_DIR/docker-compose.yml"
export COMPOSE_SERVICES_FILE="$COMPOSE_SERVICES_DIR/docker-compose.yml"

export GITLAB_RUNNERS_DIR="$DOCKER_IMAGES_DIR/gitlab-runners"
export GITLAB_RUNNERS_DOTNET_DIR="$GITLAB_RUNNERS_DIR/dotnet"
export GITLAB_RUNNERS_JAVA_DIR="$GITLAB_RUNNERS_DIR/java"
export GITLAB_RUNNERS_DOTNET_DOCKERFILE="$GITLAB_RUNNERS_DOTNET_DIR/Dockerfile"
export GITLAB_RUNNERS_JAVA_DOCKERFILE="$GITLAB_RUNNERS_JAVA_DIR/Dockerfile"

export K8S_BASE_MICROSERVICES_DIR="$K8S_BASE_DIR/microservices"

export K8S_OVERLAYS_DEV_LOCAL_DIR="$K8S_OVERLAYS_DIR/dev-local"
export K8S_DEV_LOCAL_COMMON_DIR="$K8S_OVERLAYS_DEV_LOCAL_DIR/common"
export K8S_DEV_LOCAL_MICROSERVICES_DIR="$K8S_OVERLAYS_DEV_LOCAL_DIR/microservices"



