include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

accounts-service-deploy:
  stage: deploy
  extends:
    - .setup-gradle
    - .setup-credentials
    - .setup-image
  needs:
    - job: accounts-service-publish-image
      artifacts: true
  variables:
    SERVICE_NAME: accounts-service

  script:
    - cd $K8S_DIR/overlays/dev-k8s/accounts-service

    - kustomize edit set image $SERVICE_NAME=$IMAGE_ECR_TAG

    - kubectl apply -k .