include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

accounts-service-test:
  stage: test
  extends:
    - .setup-gradle
    - .setup-credentials
    - .setup-image

  script:
    - cd $ACCOUNTS_SERVICE_DIR
    - chmod +x ./gradlew
    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - $ACCOUNTS_SERVICE_DIR/build/reports/tests/test
    reports:
      junit:
        - $ACCOUNTS_SERVICE_DIR/build/test-results/test/*.xml