gateway-deploy:
  stage: deploy
  extends:
    - .setup-image
  needs:
    - job: gateway-publish-image
      artifacts: true
    - job: gateway-test
      artifacts: true

  script:
    - cd $K8S_DIR/overlays/dev-k8s/gateway

    - kustomize edit set image $PROJECT_NAME=$IMAGE_ECR_TAG

    - kubectl apply -k .