include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

gateway-test:
  stage: test
  extends:
    - .setup-gradle
    - .setup-credentials
    - .setup-image

  script:
    - echo "GRADLE_USER_HOME => $GRADLE_USER_HOME"
    - echo $GRADLE_USER_HOME

    - echo "SERVICE_NAME => $SERVICE_NAME"
    - echo $SERVICE_NAME

    - echo "SERVICE_DIR => $SERVICE_DIR"
    - echo $SERVICE_DIR

    - echo "SERVICE_DIR_TEST => $SERVICE_DIR_TEST"
    - echo $SERVICE_DIR_TEST

    - echo "SERVICE_DIR_TEST_2 => $SERVICE_DIR_TEST_2"
    - echo $SERVICE_DIR_TEST_2

    - cd $GATEWAY_DIR
    - chmod +x ./gradlew
    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - services/gateway/build/reports/tests/test
    reports:
      junit:
        - services/gateway/build/test-results/test/*.xml