include:
  - local: '/infra/ci/gitlab/templates/setup-env.yml'

gateway-test:
  stage: test
  variables:
    GRADLE_USER_HOME: "$GATEWAY_DIR/.gradle"
  extends:
    - .setup-gradle
    - .setup-credentials
    - .setup-image

  script:
    - echo "GRADLE_USER_HOME => $GRADLE_USER_HOME"
    - cd $GATEWAY_DIR
    - chmod +x ./gradlew
    - ./gradlew test --build-cache --parallel

  artifacts:
    when: always
    paths:
      - "$GATEWAY_DIR/build/reports/tests/test"
    reports:
      junit:
        - services/gateway/build/test-results/test/*.xml