include:
  - local: $GITLAB_TEMPLATES_DIR/services/test.yml
  - local: $GITLAB_TEMPLATES_DIR/services/publish.yml
  - local: $GITLAB_TEMPLATES_DIR/services/deploy.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local