services:
  config-server-srv:
    image: config-server:dev-compose
    container_name: config-server
    build:
      context: ../../../services/config-server
      dockerfile: Dockerfile
    volumes:
      - ../../../../distributed-systems-architecture-properties:/dsa-properties-repository
    environment:
      SPRING_PROFILES_ACTIVE: native
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 20

  gateway-srv:
    image: gateway:dev-compose
    container_name: gateway
    build:
      context: ../../../services/gateway
      dockerfile: Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8222:8222"
    depends_on:
      config-server-srv:
        condition: service_healthy
      authentication-service-srv:
        condition: service_started
      accounts-service-srv:
        condition: service_started
      audit-service-srv:
        condition: service_started
      media-generation-service-srv:
        condition: service_started
      content-service-srv:
        condition: service_started


  authentication-service-srv:
    image: authentication-service:dev-compose
    container_name: authentication-service
    build:
      context: ../../../services/authentication-service
      dockerfile: Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      config-server-srv:
        condition: service_healthy

  accounts-service-srv:
    image: accounts-service:dev-compose
    container_name: accounts-service
    build:
      context: ../../../services/accounts-service
      dockerfile: Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8082:8082"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      config-server-srv:
        condition: service_healthy

  audit-service-srv:
    image: audit-service:dev-compose
    container_name: audit-service
    build:
      context: ../../../services/audit-service
      dockerfile: Dockerfile
      args:
        AWS_CODEARTIFACT_AUTH_TOKEN: "${AWS_CODEARTIFACT_AUTH_TOKEN}"
    environment:
      SPRING_PROFILES_ACTIVE: dev-compose
      CONFIG_IMPORT: configserver:http://config-server-srv:8888
    ports:
      - "8083:8083"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      config-server-srv:
        condition: service_healthy

  media-generation-service-srv:
    image: media-generation-service:dev-compose
    container_name: media-generation-service
    build:
      context: ../../../services/media-generation-service
      dockerfile: MediaGenerationService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: dev-compose
      SPRING_CLOUD_URL: http://config-server-srv:8888
    ports:
      - "8084:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      config-server-srv:
        condition: service_healthy

  content-service-srv:
    image: content-service:dev-compose
    container_name: content-service
    build:
      context: ../../../services/content-service
      dockerfile: ContentService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: dev-compose
      SPRING_CLOUD_URL: http://config-server-srv:8888
    ports:
      - "8085:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      config-server-srv:
        condition: service_healthy


networks:
  default:
    external: true
    name: distributed-systems