include:
  - local: '$INFRA_DIR/ci/gitlab/templates/setup-env.yml'
  - local: '$INFRA_DIR/ci/gitlab/templates/$PROJECT_DIR/test.yml'
  - local: '$INFRA_DIR/ci/gitlab/templates/$PROJECT_DIR/publish.yml'

stages:
  - test
  - publish

default:
  tags:
    - local