include:
  - local: '/infra/ci/gitlab/templates/artifacts/shared-starter/test.yml'
  - local: '/infra/ci/gitlab/templates/artifacts/shared-starter/publish.yml'

default:
  tags:
    - local

stages:
  - test
  - publish