include:
  - local: $GITLAB_TEMPLATES_DIR/$PROJECT_TYPE/test.yml
  - local: $GITLAB_TEMPLATES_DIR/$PROJECT_TYPE/publish.yml
  - local: $GITLAB_TEMPLATES_DIR/$PROJECT_TYPE/deploy.yml

stages:
  - test
  - publish
  - deploy

default:
  tags:
    - local